eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

microservice:
  product-service:
    endpoint:
      uri: http://PRODUCT-SERVICE/product_test
  category-service:
    endpoint:
      uri: http://CATEGORY-SERVICE/category
