#Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

#LOGGER
logging:
  level:
    ROOT: ERROR
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
    com:
      netflix:
        discovery: 'OFF'

#URL
microservice:
  product-service:
    endpoint:
      uri: http://PRODUCT-SERVICE/product
  category-service:
    endpoint:
      uri: http://CATEGORY-SERVICE/category
      
